version: '3'

services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: flaskapp
      POSTGRES_PASSWORD: flaskapp
      POSTGRES_DB: teammanagement

  flask_app:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://flaskapp:flaskapp@db/teammanagement
